### Manipulando Strings

In [0]:
# lendo os arquivos de dados de voos
df = spark\
.read\
.option("inferSchema", "True")\
.option("header", "True")\
.json("/FileStore/tables/bronze/*.json")

In [0]:
df.show(10)

+-----------------+-------------------+-----+
|DEST_COUNTRY_NAME|ORIGIN_COUNTRY_NAME|count|
+-----------------+-------------------+-----+
|    United States|            Romania|   15|
|    United States|            Croatia|    1|
|    United States|            Ireland|  344|
|            Egypt|      United States|   15|
|    United States|              India|   62|
|    United States|          Singapore|    1|
|    United States|            Grenada|   62|
|       Costa Rica|      United States|  588|
|          Senegal|      United States|   40|
|          Moldova|      United States|    1|
+-----------------+-------------------+-----+
only showing top 10 rows

In [0]:
df.count()

Out[4]: 1502

In [0]:
# valores em minúsculo
from pyspark.sql.functions import lower, upper, col
df.select(col("DEST_COUNTRY_NAME"), lower(col("DEST_COUNTRY_NAME"))).show(10)

+-----------------+------------------------+
|DEST_COUNTRY_NAME|lower(DEST_COUNTRY_NAME)|
+-----------------+------------------------+
|    United States|           united states|
|    United States|           united states|
|    United States|           united states|
|            Egypt|                   egypt|
|    United States|           united states|
|    United States|           united states|
|    United States|           united states|
|       Costa Rica|              costa rica|
|          Senegal|                 senegal|
|          Moldova|                 moldova|
+-----------------+------------------------+
only showing top 10 rows

In [0]:
# valores em maiúsculo
from pyspark.sql.functions import lower, upper, col
df.select(col("DEST_COUNTRY_NAME"), upper(col("DEST_COUNTRY_NAME"))).show(10)

+-----------------+------------------------+
|DEST_COUNTRY_NAME|upper(DEST_COUNTRY_NAME)|
+-----------------+------------------------+
|    United States|           UNITED STATES|
|    United States|           UNITED STATES|
|    United States|           UNITED STATES|
|            Egypt|                   EGYPT|
|    United States|           UNITED STATES|
|    United States|           UNITED STATES|
|    United States|           UNITED STATES|
|       Costa Rica|              COSTA RICA|
|          Senegal|                 SENEGAL|
|          Moldova|                 MOLDOVA|
+-----------------+------------------------+
only showing top 10 rows

In [0]:
# remove espaços em branco na esquerda
from pyspark.sql.functions import ltrim
df.select(ltrim(col("DEST_COUNTRY_NAME"))).show(5)

+------------------------+
|ltrim(DEST_COUNTRY_NAME)|
+------------------------+
|           United States|
|           United States|
|           United States|
|                   Egypt|
|           United States|
+------------------------+
only showing top 5 rows

In [0]:
# remove espaços em branco na direita
from pyspark.sql.functions import rtrim
df.select(ltrim(col("DEST_COUNTRY_NAME"))).show(5)

+------------------------+
|ltrim(DEST_COUNTRY_NAME)|
+------------------------+
|           United States|
|           United States|
|           United States|
|                   Egypt|
|           United States|
+------------------------+
only showing top 5 rows

In [0]:
# algumas funções para tratamentos de strings
from pyspark.sql.functions import lit, ltrim, rtrim, trim, lpad, rpad
df.select(
ltrim(lit("  HELLO  ")).alias("ltrim"), # remove espaços a esquerda
ltrim(lit("  HELLO  ")).alias("rtrim"), # remove espaços a direita
ltrim(lit("  HELLO  ")).alias("trim"), # remove espaços a esqueda e direita
lpad(lit("HELLO"), 3, "").alias("lp"), # imprime até o número do caracter especificado
rpad(lit("HELLO"), 10, "0").alias("rp")).show(5) # completa a quantidade de caracteres especificados com o valor nas ""

+-------+-------+-------+---+----------+
|  ltrim|  rtrim|   trim| lp|        rp|
+-------+-------+-------+---+----------+
|HELLO  |HELLO  |HELLO  |HEL|HELLO00000|
|HELLO  |HELLO  |HELLO  |HEL|HELLO00000|
|HELLO  |HELLO  |HELLO  |HEL|HELLO00000|
|HELLO  |HELLO  |HELLO  |HEL|HELLO00000|
|HELLO  |HELLO  |HELLO  |HEL|HELLO00000|
+-------+-------+-------+---+----------+
only showing top 5 rows

### Estatística descritiva básica:

* mean() - Retorna o valor médio de cada grupo;
* max() - Retorna o valor máximo de cada grupo;
* min() - Retorna o valor mínimo de cada grupo;
* sum() - Retorna a soma de todos os valores do grupo;
* avg() - Retorna o valor médio de cada grupo;

In [0]:
# lendo dataset
df = spark.read.format("csv")\
.option("header", "true")\
.option("inferSchema", "true")\
.load("/FileStore/tables/bronze2/retail_2010_12_01.csv")

In [0]:
df.show(10)

+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
|InvoiceNo|StockCode|         Description|Quantity|        InvoiceDate|UnitPrice|CustomerID|       Country|
+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
|   536365|   85123A|WHITE HANGING HEA...|       6|2010-12-01 08:26:00|     2.55|   17850.0|United Kingdom|
|   536365|    71053| WHITE METAL LANTERN|       6|2010-12-01 08:26:00|     3.39|   17850.0|United Kingdom|
|   536365|   84406B|CREAM CUPID HEART...|       8|2010-12-01 08:26:00|     2.75|   17850.0|United Kingdom|
|   536365|   84029G|KNITTED UNION FLA...|       6|2010-12-01 08:26:00|     3.39|   17850.0|United Kingdom|
|   536365|   84029E|RED WOOLLY HOTTIE...|       6|2010-12-01 08:26:00|     3.39|   17850.0|United Kingdom|
|   536365|    22752|SET 7 BABUSHKA NE...|       2|2010-12-01 08:26:00|     7.65|   17850.0|United Kingdom|
|   536365|    21730|GLASS STAR FROSTE...|       6|2010-12-01 08:26:00|     4.25|   17850.0|United Kingdom|
|   536366|    22633|HAND WARMER UNION...|       6|2010-12-01 08:28:00|     1.85|   17850.0|United Kingdom|
|   536366|    22632|HAND WARMER RED P...|       6|2010-12-01 08:28:00|     1.85|   17850.0|United Kingdom|
|   536367|    84879|ASSORTED COLOUR B...|      32|2010-12-01 08:34:00|     1.69|   13047.0|United Kingdom|
+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
only showing top 10 rows

In [0]:
# soma de preços unitários por país
df.groupBy("Country").sum("UnitPrice").show(10)

+--------------+------------------+
|       Country|    sum(UnitPrice)|
+--------------+------------------+
|       Germany| 93.82000000000002|
|        France|             55.29|
|          EIRE|133.64000000000001|
|        Norway|            102.67|
|     Australia|              73.9|
|United Kingdom|12428.080000000024|
|   Netherlands|             16.85|
+--------------+------------------+

In [0]:
# conta a quantidade de paises distintos
df.groupBy("Country").count().show()

+--------------+-----+
|       Country|count|
+--------------+-----+
|       Germany|   29|
|        France|   20|
|          EIRE|   21|
|        Norway|   73|
|     Australia|   14|
|United Kingdom| 2949|
|   Netherlands|    2|
+--------------+-----+

In [0]:
# retorna o valor mínimo do grupo
df.groupBy("Country").min("UnitPrice").show()

+--------------+--------------+
|       Country|min(UnitPrice)|
+--------------+--------------+
|       Germany|          0.42|
|        France|          0.42|
|          EIRE|          0.65|
|        Norway|          0.29|
|     Australia|          0.85|
|United Kingdom|           0.0|
|   Netherlands|          1.85|
+--------------+--------------+

In [0]:
# retorna o valor máximo do grupo
df.groupBy("Country").max("UnitPrice").show()

+--------------+--------------+
|       Country|max(UnitPrice)|
+--------------+--------------+
|       Germany|          18.0|
|        France|          18.0|
|          EIRE|          50.0|
|        Norway|          7.95|
|     Australia|           8.5|
|United Kingdom|        607.49|
|   Netherlands|          15.0|
+--------------+--------------+

In [0]:
# retorna a média do grupo
df.groupBy("Country").avg("UnitPrice").show()

+--------------+------------------+
|       Country|    avg(UnitPrice)|
+--------------+------------------+
|       Germany| 3.235172413793104|
|        France|            2.7645|
|          EIRE|6.3638095238095245|
|        Norway|1.4064383561643836|
|     Australia| 5.278571428571429|
|United Kingdom|4.2143370634113335|
|   Netherlands|             8.425|
+--------------+------------------+

In [0]:
# retorna a média do grupo
df.groupBy("Country").mean("UnitPrice").show()

+--------------+------------------+
|       Country|    avg(UnitPrice)|
+--------------+------------------+
|       Germany| 3.235172413793104|
|        France|            2.7645|
|          EIRE|6.3638095238095245|
|        Norway|1.4064383561643836|
|     Australia| 5.278571428571429|
|United Kingdom|4.2143370634113335|
|   Netherlands|             8.425|
+--------------+------------------+

In [0]:
# agrupa várias colunas
df.groupBy("Country", "InvoiceDate")\
.sum("UnitPrice").show()

+--------------+-------------------+------------------+
|       Country|        InvoiceDate|    sum(UnitPrice)|
+--------------+-------------------+------------------+
|United Kingdom|2010-12-01 12:22:00| 51.13000000000001|
|United Kingdom|2010-12-01 14:34:00| 78.78000000000002|
|United Kingdom|2010-12-01 14:41:00|251.68999999999983|
|United Kingdom|2010-12-01 09:32:00|             59.11|
|United Kingdom|2010-12-01 13:21:00|109.90000000000003|
|United Kingdom|2010-12-01 16:16:00|              2.51|
|United Kingdom|2010-12-01 12:49:00|146.18999999999997|
|United Kingdom|2010-12-01 17:06:00| 3612.350000000002|
|United Kingdom|2010-12-01 13:38:00| 58.20000000000002|
|United Kingdom|2010-12-01 09:01:00|               3.7|
|United Kingdom|2010-12-01 12:35:00|              42.2|
|United Kingdom|2010-12-01 12:48:00|              4.95|
|United Kingdom|2010-12-01 12:38:00|              5.86|
|United Kingdom|2010-12-01 17:29:00|             34.34|
|United Kingdom|2010-12-01 12:12:00|             10.58|
|United Kingdom|2010-12-01 15:40:00| 50.55000000000002|
|United Kingdom|2010-12-01 16:19:00|              1.65|
|United Kingdom|2010-12-01 09:49:00|              4.65|
|United Kingdom|2010-12-01 11:57:00|            116.43|
|United Kingdom|2010-12-01 12:15:00|60.129999999999995|
+--------------+-------------------+------------------+
only showing top 20 rows