### Manipulando Strings

In [ ]:
# lendo os arquivos de dados de voos
df = spark\
.read\
.option("inferSchema", "True")\
.option("header", "True")\
.json("/FileStore/tables/bronze/*.json")

In [ ]:
df.show(10)

+-----------------+-------------------+-----+
|DEST_COUNTRY_NAME|ORIGIN_COUNTRY_NAME|count|
+-----------------+-------------------+-----+
|    United States|            Romania|   15|
|    United States|            Croatia|    1|
|    United States|            Ireland|  344|
|            Egypt|      United States|   15|
|    United States|              India|   62|
|    United States|          Singapore|    1|
|    United States|            Grenada|   62|
|       Costa Rica|      United States|  588|
|          Senegal|      United States|   40|
|          Moldova|      United States|    1|
+-----------------+-------------------+-----+
only showing top 10 rows

In [ ]:
df.count()

Out[4]: 1502

In [ ]:
# valores em minúsculo
from pyspark.sql.functions import lower, upper, col
df.select(col("DEST_COUNTRY_NAME"), lower(col("DEST_COUNTRY_NAME"))).show(10)

+-----------------+------------------------+
|DEST_COUNTRY_NAME|lower(DEST_COUNTRY_NAME)|
+-----------------+------------------------+
|    United States|           united states|
|    United States|           united states|
|    United States|           united states|
|            Egypt|                   egypt|
|    United States|           united states|
|    United States|           united states|
|    United States|           united states|
|       Costa Rica|              costa rica|
|          Senegal|                 senegal|
|          Moldova|                 moldova|
+-----------------+------------------------+
only showing top 10 rows

In [ ]:
# valores em maiúsculo
from pyspark.sql.functions import lower, upper, col
df.select(col("DEST_COUNTRY_NAME"), upper(col("DEST_COUNTRY_NAME"))).show(10)

+-----------------+------------------------+
|DEST_COUNTRY_NAME|upper(DEST_COUNTRY_NAME)|
+-----------------+------------------------+
|    United States|           UNITED STATES|
|    United States|           UNITED STATES|
|    United States|           UNITED STATES|
|            Egypt|                   EGYPT|
|    United States|           UNITED STATES|
|    United States|           UNITED STATES|
|    United States|           UNITED STATES|
|       Costa Rica|              COSTA RICA|
|          Senegal|                 SENEGAL|
|          Moldova|                 MOLDOVA|
+-----------------+------------------------+
only showing top 10 rows

In [ ]:
# remove espaços em branco na esquerda
from pyspark.sql.functions import ltrim
df.select(ltrim(col("DEST_COUNTRY_NAME"))).show(5)

+------------------------+
|ltrim(DEST_COUNTRY_NAME)|
+------------------------+
|           United States|
|           United States|
|           United States|
|                   Egypt|
|           United States|
+------------------------+
only showing top 5 rows

In [ ]:
# remove espaços em branco na direita
from pyspark.sql.functions import rtrim
df.select(ltrim(col("DEST_COUNTRY_NAME"))).show(5)

+------------------------+
|ltrim(DEST_COUNTRY_NAME)|
+------------------------+
|           United States|
|           United States|
|           United States|
|                   Egypt|
|           United States|
+------------------------+
only showing top 5 rows

In [ ]:
# algumas funções para tratamentos de strings
from pyspark.sql.functions import lit, ltrim, rtrim, trim, lpad, rpad
df.select(
ltrim(lit("  HELLO  ")).alias("ltrim"), # remove espaços a esquerda
ltrim(lit("  HELLO  ")).alias("rtrim"), # remove espaços a direita
ltrim(lit("  HELLO  ")).alias("trim"), # remove espaços a esqueda e direita
lpad(lit("HELLO"), 3, "").alias("lp"), # imprime até o número do caracter especificado
rpad(lit("HELLO"), 10, "0").alias("rp")).show(5) # completa a quantidade de caracteres especificados com o valor nas ""

+-------+-------+-------+---+----------+
|  ltrim|  rtrim|   trim| lp|        rp|
+-------+-------+-------+---+----------+
|HELLO  |HELLO  |HELLO  |HEL|HELLO00000|
|HELLO  |HELLO  |HELLO  |HEL|HELLO00000|
|HELLO  |HELLO  |HELLO  |HEL|HELLO00000|
|HELLO  |HELLO  |HELLO  |HEL|HELLO00000|
|HELLO  |HELLO  |HELLO  |HEL|HELLO00000|
+-------+-------+-------+---+----------+
only showing top 5 rows

### Estatística descritiva básica:

* mean() - Retorna o valor médio de cada grupo;
* max() - Retorna o valor máximo de cada grupo;
* min() - Retorna o valor mínimo de cada grupo;
* sum() - Retorna a soma de todos os valores do grupo;
* avg() - Retorna o valor médio de cada grupo;

In [ ]:
# lendo dataset
df = spark.read.format("csv")\
.option("header", "true")\
.option("inferSchema", "true")\
.load("/FileStore/tables/bronze2/retail_2010_12_01.csv")

In [ ]:
df.show(10)

+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
|InvoiceNo|StockCode|         Description|Quantity|        InvoiceDate|UnitPrice|CustomerID|       Country|
+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
|   536365|   85123A|WHITE HANGING HEA...|       6|2010-12-01 08:26:00|     2.55|   17850.0|United Kingdom|
|   536365|    71053| WHITE METAL LANTERN|       6|2010-12-01 08:26:00|     3.39|   17850.0|United Kingdom|
|   536365|   84406B|CREAM CUPID HEART...|       8|2010-12-01 08:26:00|     2.75|   17850.0|United Kingdom|
|   536365|   84029G|KNITTED UNION FLA...|       6|2010-12-01 08:26:00|     3.39|   17850.0|United Kingdom|
|   536365|   84029E|RED WOOLLY HOTTIE...|       6|2010-12-01 08:26:00|     3.39|   17850.0|United Kingdom|
|   536365|    22752|SET 7 BABUSHKA NE...|       2|2010-12-01 08:26:00|     7.65|   17850.0|United Kingdom|
|   536365|    21730|GLASS STAR FROSTE...|       6|2010-12-01 08:26:00|     4.25|   17850.0|United Kingdom|
|   536366|    22633|HAND WARMER UNION...|       6|2010-12-01 08:28:00|     1.85|   17850.0|United Kingdom|
|   536366|    22632|HAND WARMER RED P...|       6|2010-12-01 08:28:00|     1.85|   17850.0|United Kingdom|
|   536367|    84879|ASSORTED COLOUR B...|      32|2010-12-01 08:34:00|     1.69|   13047.0|United Kingdom|
+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
only showing top 10 rows

In [ ]:
# soma de preços unitários por país
df.groupBy("Country").sum("UnitPrice").show(10)

+--------------+------------------+
|       Country|    sum(UnitPrice)|
+--------------+------------------+
|       Germany| 93.82000000000002|
|        France|             55.29|
|          EIRE|133.64000000000001|
|        Norway|            102.67|
|     Australia|              73.9|
|United Kingdom|12428.080000000024|
|   Netherlands|             16.85|
+--------------+------------------+

In [ ]:
# conta a quantidade de paises distintos
df.groupBy("Country").count().show()

+--------------+-----+
|       Country|count|
+--------------+-----+
|       Germany|   29|
|        France|   20|
|          EIRE|   21|
|        Norway|   73|
|     Australia|   14|
|United Kingdom| 2949|
|   Netherlands|    2|
+--------------+-----+

In [ ]:
# retorna o valor mínimo do grupo
df.groupBy("Country").min("UnitPrice").show()

+--------------+--------------+
|       Country|min(UnitPrice)|
+--------------+--------------+
|       Germany|          0.42|
|        France|          0.42|
|          EIRE|          0.65|
|        Norway|          0.29|
|     Australia|          0.85|
|United Kingdom|           0.0|
|   Netherlands|          1.85|
+--------------+--------------+

In [ ]:
# retorna o valor máximo do grupo
df.groupBy("Country").max("UnitPrice").show()

+--------------+--------------+
|       Country|max(UnitPrice)|
+--------------+--------------+
|       Germany|          18.0|
|        France|          18.0|
|          EIRE|          50.0|
|        Norway|          7.95|
|     Australia|           8.5|
|United Kingdom|        607.49|
|   Netherlands|          15.0|
+--------------+--------------+

In [ ]:
# retorna a média do grupo
df.groupBy("Country").avg("UnitPrice").show()

+--------------+------------------+
|       Country|    avg(UnitPrice)|
+--------------+------------------+
|       Germany| 3.235172413793104|
|        France|            2.7645|
|          EIRE|6.3638095238095245|
|        Norway|1.4064383561643836|
|     Australia| 5.278571428571429|
|United Kingdom|4.2143370634113335|
|   Netherlands|             8.425|
+--------------+------------------+

In [ ]:
# retorna a média do grupo
df.groupBy("Country").mean("UnitPrice").show()

+--------------+------------------+
|       Country|    avg(UnitPrice)|
+--------------+------------------+
|       Germany| 3.235172413793104|
|        France|            2.7645|
|          EIRE|6.3638095238095245|
|        Norway|1.4064383561643836|
|     Australia| 5.278571428571429|
|United Kingdom|4.2143370634113335|
|   Netherlands|             8.425|
+--------------+------------------+

In [ ]:
# agrupa várias colunas
df.groupBy("Country", "InvoiceDate")\
.sum("UnitPrice").show()

+--------------+-------------------+------------------+
|       Country|        InvoiceDate|    sum(UnitPrice)|
+--------------+-------------------+------------------+
|United Kingdom|2010-12-01 12:22:00| 51.13000000000001|
|United Kingdom|2010-12-01 14:34:00| 78.78000000000002|
|United Kingdom|2010-12-01 14:41:00|251.68999999999983|
|United Kingdom|2010-12-01 09:32:00|             59.11|
|United Kingdom|2010-12-01 13:21:00|109.90000000000003|
|United Kingdom|2010-12-01 16:16:00|              2.51|
|United Kingdom|2010-12-01 12:49:00|146.18999999999997|
|United Kingdom|2010-12-01 17:06:00| 3612.350000000002|
|United Kingdom|2010-12-01 13:38:00| 58.20000000000002|
|United Kingdom|2010-12-01 09:01:00|               3.7|
|United Kingdom|2010-12-01 12:35:00|              42.2|
|United Kingdom|2010-12-01 12:48:00|              4.95|
|United Kingdom|2010-12-01 12:38:00|              5.86|
|United Kingdom|2010-12-01 17:29:00|             34.34|
|United Kingdom|2010-12-01 12:12:00|             10.58|
|United Kingdom|2010-12-01 15:40:00| 50.55000000000002|
|United Kingdom|2010-12-01 16:19:00|              1.65|
|United Kingdom|2010-12-01 09:49:00|              4.65|
|United Kingdom|2010-12-01 11:57:00|            116.43|
|United Kingdom|2010-12-01 12:15:00|60.129999999999995|
+--------------+-------------------+------------------+
only showing top 20 rows

### Trabalhando com datas
* Algums funções mais usadas:
  * current_day():
  * date_format(dateExpr,format):
  * to_date():
  * to_date(column, fmt):
  * add_months(column, numMonths):
  * date_add(column, days):
  * date_sub(column, days):
  * datediff(end, start):
  * current_timestamp():
  * hour(column)

In [ ]:
df.show()

+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
|InvoiceNo|StockCode|         Description|Quantity|        InvoiceDate|UnitPrice|CustomerID|       Country|
+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
|   536365|   85123A|WHITE HANGING HEA...|       6|2010-12-01 08:26:00|     2.55|   17850.0|United Kingdom|
|   536365|    71053| WHITE METAL LANTERN|       6|2010-12-01 08:26:00|     3.39|   17850.0|United Kingdom|
|   536365|   84406B|CREAM CUPID HEART...|       8|2010-12-01 08:26:00|     2.75|   17850.0|United Kingdom|
|   536365|   84029G|KNITTED UNION FLA...|       6|2010-12-01 08:26:00|     3.39|   17850.0|United Kingdom|
|   536365|   84029E|RED WOOLLY HOTTIE...|       6|2010-12-01 08:26:00|     3.39|   17850.0|United Kingdom|
|   536365|    22752|SET 7 BABUSHKA NE...|       2|2010-12-01 08:26:00|     7.65|   17850.0|United Kingdom|
|   536365|    21730|GLASS STAR FROSTE...|       6|2010-12-01 08:26:00|     4.25|   17850.0|United Kingdom|
|   536366|    22633|HAND WARMER UNION...|       6|2010-12-01 08:28:00|     1.85|   17850.0|United Kingdom|
|   536366|    22632|HAND WARMER RED P...|       6|2010-12-01 08:28:00|     1.85|   17850.0|United Kingdom|
|   536367|    84879|ASSORTED COLOUR B...|      32|2010-12-01 08:34:00|     1.69|   13047.0|United Kingdom|
|   536367|    22745|POPPY'S PLAYHOUSE...|       6|2010-12-01 08:34:00|      2.1|   13047.0|United Kingdom|
|   536367|    22748|POPPY'S PLAYHOUSE...|       6|2010-12-01 08:34:00|      2.1|   13047.0|United Kingdom|
|   536367|    22749|FELTCRAFT PRINCES...|       8|2010-12-01 08:34:00|     3.75|   13047.0|United Kingdom|
|   536367|    22310|IVORY KNITTED MUG...|       6|2010-12-01 08:34:00|     1.65|   13047.0|United Kingdom|
|   536367|    84969|BOX OF 6 ASSORTED...|       6|2010-12-01 08:34:00|     4.25|   13047.0|United Kingdom|
|   536367|    22623|BOX OF VINTAGE JI...|       3|2010-12-01 08:34:00|     4.95|   13047.0|United Kingdom|
|   536367|    22622|BOX OF VINTAGE AL...|       2|2010-12-01 08:34:00|     9.95|   13047.0|United Kingdom|
|   536367|    21754|HOME BUILDING BLO...|       3|2010-12-01 08:34:00|     5.95|   13047.0|United Kingdom|
|   536367|    21755|LOVE BUILDING BLO...|       3|2010-12-01 08:34:00|     5.95|   13047.0|United Kingdom|
|   536367|    21777|RECIPE BOX WITH M...|       4|2010-12-01 08:34:00|     7.95|   13047.0|United Kingdom|
+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
only showing top 20 rows

In [ ]:
df.printSchema()

root
 |-- InvoiceNo: string (nullable = true)
 |-- StockCode: string (nullable = true)
 |-- Description: string (nullable = true)
 |-- Quantity: integer (nullable = true)
 |-- InvoiceDate: timestamp (nullable = true)
 |-- UnitPrice: double (nullable = true)
 |-- CustomerID: double (nullable = true)
 |-- Country: string (nullable = true)

In [ ]:
from pyspark.sql.functions import *
#current_date()
df.select(current_date().alias("current_date")).show(1)

+------------+
|current_date|
+------------+
|  2023-03-12|
+------------+
only showing top 1 row

In [ ]:
# formata valores de data
df.select(col("InvoiceDate"), \
        date_format(col("InvoiceDate"), "dd/MM/yyyy hh:mm:ss")\
        .alias("Formato Brasil")).show()

+-------------------+-------------------+
|        InvoiceDate|     Formato Brasil|
+-------------------+-------------------+
|2010-12-01 08:26:00|01/12/2010 08:26:00|
|2010-12-01 08:26:00|01/12/2010 08:26:00|
|2010-12-01 08:26:00|01/12/2010 08:26:00|
|2010-12-01 08:26:00|01/12/2010 08:26:00|
|2010-12-01 08:26:00|01/12/2010 08:26:00|
|2010-12-01 08:26:00|01/12/2010 08:26:00|
|2010-12-01 08:26:00|01/12/2010 08:26:00|
|2010-12-01 08:28:00|01/12/2010 08:28:00|
|2010-12-01 08:28:00|01/12/2010 08:28:00|
|2010-12-01 08:34:00|01/12/2010 08:34:00|
|2010-12-01 08:34:00|01/12/2010 08:34:00|
|2010-12-01 08:34:00|01/12/2010 08:34:00|
|2010-12-01 08:34:00|01/12/2010 08:34:00|
|2010-12-01 08:34:00|01/12/2010 08:34:00|
|2010-12-01 08:34:00|01/12/2010 08:34:00|
|2010-12-01 08:34:00|01/12/2010 08:34:00|
|2010-12-01 08:34:00|01/12/2010 08:34:00|
|2010-12-01 08:34:00|01/12/2010 08:34:00|
|2010-12-01 08:34:00|01/12/2010 08:34:00|
|2010-12-01 08:34:00|01/12/2010 08:34:00|
+-------------------+-------------------+
only showing top 20 rows

In [ ]:
# diferença entre duas datas
df.select(col("InvoiceDate"),
          datediff(current_date(),col("InvoiceDate")). alias("Diferença")).show()

+-------------------+---------+
|        InvoiceDate|Diferença|
+-------------------+---------+
|2010-12-01 08:26:00|     4484|
|2010-12-01 08:26:00|     4484|
|2010-12-01 08:26:00|     4484|
|2010-12-01 08:26:00|     4484|
|2010-12-01 08:26:00|     4484|
|2010-12-01 08:26:00|     4484|
|2010-12-01 08:26:00|     4484|
|2010-12-01 08:28:00|     4484|
|2010-12-01 08:28:00|     4484|
|2010-12-01 08:34:00|     4484|
|2010-12-01 08:34:00|     4484|
|2010-12-01 08:34:00|     4484|
|2010-12-01 08:34:00|     4484|
|2010-12-01 08:34:00|     4484|
|2010-12-01 08:34:00|     4484|
|2010-12-01 08:34:00|     4484|
|2010-12-01 08:34:00|     4484|
|2010-12-01 08:34:00|     4484|
|2010-12-01 08:34:00|     4484|
|2010-12-01 08:34:00|     4484|
+-------------------+---------+
only showing top 20 rows

In [ ]:
# meses entre datas
df.select(col("InvoiceDate"),
         months_between(current_date(),col("InvoiceDate")).alias("difenreça de meses")).show()

+-------------------+------------------+
|        InvoiceDate|difenreça de meses|
+-------------------+------------------+
|2010-12-01 08:26:00|      147.34350358|
|2010-12-01 08:26:00|      147.34350358|
|2010-12-01 08:26:00|      147.34350358|
|2010-12-01 08:26:00|      147.34350358|
|2010-12-01 08:26:00|      147.34350358|
|2010-12-01 08:26:00|      147.34350358|
|2010-12-01 08:26:00|      147.34350358|
|2010-12-01 08:28:00|      147.34345878|
|2010-12-01 08:28:00|      147.34345878|
|2010-12-01 08:34:00|      147.34332437|
|2010-12-01 08:34:00|      147.34332437|
|2010-12-01 08:34:00|      147.34332437|
|2010-12-01 08:34:00|      147.34332437|
|2010-12-01 08:34:00|      147.34332437|
|2010-12-01 08:34:00|      147.34332437|
|2010-12-01 08:34:00|      147.34332437|
|2010-12-01 08:34:00|      147.34332437|
|2010-12-01 08:34:00|      147.34332437|
|2010-12-01 08:34:00|      147.34332437|
|2010-12-01 08:34:00|      147.34332437|
+-------------------+------------------+
only showing top 20 rows

In [ ]:
# extrai ano, mês, dia do mês, semana do ano
df.select(col("InvoiceDate"),
         year(col("InvoiceDate")).alias("ANO"),
         month(col("InvoiceDate")).alias("MONTH"),
         next_day(col("InvoiceDate"), "Sunday").alias("PRÓXIMO_DIA"),
         weekofyear(col("InvoiceDate")).alias("SEMANA_DO_ANO")).show()

+-------------------+----+-----+-----------+-------------+
|        InvoiceDate| ANO|MONTH|PRÓXIMO_DIA|SEMANA_DO_ANO|
+-------------------+----+-----+-----------+-------------+
|2010-12-01 08:26:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:26:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:26:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:26:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:26:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:26:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:26:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:28:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:28:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:34:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:34:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:34:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:34:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:34:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:34:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:34:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:34:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:34:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:34:00|2010|   12| 2010-12-05|           48|
|2010-12-01 08:34:00|2010|   12| 2010-12-05|           48|
+-------------------+----+-----+-----------+-------------+
only showing top 20 rows

In [ ]:
# dia da semana, dia do mês, dias do ano
df.select(col("InvoiceDate"),
         dayofweek(col("InvoiceDate")).alias("dia_da_semana"),
         dayofmonth(col("InvoiceDate")).alias("dia_do_mes"),
         dayofyear(col("InvoiceDate")).alias("dia_do_ano")).show()

+-------------------+-------------+----------+----------+
|        InvoiceDate|dia_da_semana|dia_do_mes|dia_do_ano|
+-------------------+-------------+----------+----------+
|2010-12-01 08:26:00|            4|         1|       335|
|2010-12-01 08:26:00|            4|         1|       335|
|2010-12-01 08:26:00|            4|         1|       335|
|2010-12-01 08:26:00|            4|         1|       335|
|2010-12-01 08:26:00|            4|         1|       335|
|2010-12-01 08:26:00|            4|         1|       335|
|2010-12-01 08:26:00|            4|         1|       335|
|2010-12-01 08:28:00|            4|         1|       335|
|2010-12-01 08:28:00|            4|         1|       335|
|2010-12-01 08:34:00|            4|         1|       335|
|2010-12-01 08:34:00|            4|         1|       335|
|2010-12-01 08:34:00|            4|         1|       335|
|2010-12-01 08:34:00|            4|         1|       335|
|2010-12-01 08:34:00|            4|         1|       335|
|2010-12-01 08:34:00|            4|         1|       335|
|2010-12-01 08:34:00|            4|         1|       335|
|2010-12-01 08:34:00|            4|         1|       335|
|2010-12-01 08:34:00|            4|         1|       335|
|2010-12-01 08:34:00|            4|         1|       335|
|2010-12-01 08:34:00|            4|         1|       335|
+-------------------+-------------+----------+----------+
only showing top 20 rows

In [ ]:
# imprime o timestamp atual
df.select(current_timestamp().alias("current_timestamp")).show(1, truncate=False)

+-----------------------+
|current_timestamp      |
+-----------------------+
|2023-03-12 18:18:39.357|
+-----------------------+
only showing top 1 row

In [ ]:
# retorna hora, minuto e segundo
df.select(col("InvoiceDate"),
         hour(col("InvoiceDate")).alias("hora"),
         minute(col("InvoiceDate")).alias("minuto"),
         second(col("InvoiceDate")).alias("segundo")).show()

+-------------------+----+------+-------+
|        InvoiceDate|hora|minuto|segundo|
+-------------------+----+------+-------+
|2010-12-01 08:26:00|   8|    26|      0|
|2010-12-01 08:26:00|   8|    26|      0|
|2010-12-01 08:26:00|   8|    26|      0|
|2010-12-01 08:26:00|   8|    26|      0|
|2010-12-01 08:26:00|   8|    26|      0|
|2010-12-01 08:26:00|   8|    26|      0|
|2010-12-01 08:26:00|   8|    26|      0|
|2010-12-01 08:28:00|   8|    28|      0|
|2010-12-01 08:28:00|   8|    28|      0|
|2010-12-01 08:34:00|   8|    34|      0|
|2010-12-01 08:34:00|   8|    34|      0|
|2010-12-01 08:34:00|   8|    34|      0|
|2010-12-01 08:34:00|   8|    34|      0|
|2010-12-01 08:34:00|   8|    34|      0|
|2010-12-01 08:34:00|   8|    34|      0|
|2010-12-01 08:34:00|   8|    34|      0|
|2010-12-01 08:34:00|   8|    34|      0|
|2010-12-01 08:34:00|   8|    34|      0|
|2010-12-01 08:34:00|   8|    34|      0|
|2010-12-01 08:34:00|   8|    34|      0|
+-------------------+----+------+-------+
only showing top 20 rows

### Condições com operadores boleanos

In [ ]:
df.show()

+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
|InvoiceNo|StockCode|         Description|Quantity|        InvoiceDate|UnitPrice|CustomerID|       Country|
+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
|   536365|   85123A|WHITE HANGING HEA...|       6|2010-12-01 08:26:00|     2.55|   17850.0|United Kingdom|
|   536365|    71053| WHITE METAL LANTERN|       6|2010-12-01 08:26:00|     3.39|   17850.0|United Kingdom|
|   536365|   84406B|CREAM CUPID HEART...|       8|2010-12-01 08:26:00|     2.75|   17850.0|United Kingdom|
|   536365|   84029G|KNITTED UNION FLA...|       6|2010-12-01 08:26:00|     3.39|   17850.0|United Kingdom|
|   536365|   84029E|RED WOOLLY HOTTIE...|       6|2010-12-01 08:26:00|     3.39|   17850.0|United Kingdom|
|   536365|    22752|SET 7 BABUSHKA NE...|       2|2010-12-01 08:26:00|     7.65|   17850.0|United Kingdom|
|   536365|    21730|GLASS STAR FROSTE...|       6|2010-12-01 08:26:00|     4.25|   17850.0|United Kingdom|
|   536366|    22633|HAND WARMER UNION...|       6|2010-12-01 08:28:00|     1.85|   17850.0|United Kingdom|
|   536366|    22632|HAND WARMER RED P...|       6|2010-12-01 08:28:00|     1.85|   17850.0|United Kingdom|
|   536367|    84879|ASSORTED COLOUR B...|      32|2010-12-01 08:34:00|     1.69|   13047.0|United Kingdom|
|   536367|    22745|POPPY'S PLAYHOUSE...|       6|2010-12-01 08:34:00|      2.1|   13047.0|United Kingdom|
|   536367|    22748|POPPY'S PLAYHOUSE...|       6|2010-12-01 08:34:00|      2.1|   13047.0|United Kingdom|
|   536367|    22749|FELTCRAFT PRINCES...|       8|2010-12-01 08:34:00|     3.75|   13047.0|United Kingdom|
|   536367|    22310|IVORY KNITTED MUG...|       6|2010-12-01 08:34:00|     1.65|   13047.0|United Kingdom|
|   536367|    84969|BOX OF 6 ASSORTED...|       6|2010-12-01 08:34:00|     4.25|   13047.0|United Kingdom|
|   536367|    22623|BOX OF VINTAGE JI...|       3|2010-12-01 08:34:00|     4.95|   13047.0|United Kingdom|
|   536367|    22622|BOX OF VINTAGE AL...|       2|2010-12-01 08:34:00|     9.95|   13047.0|United Kingdom|
|   536367|    21754|HOME BUILDING BLO...|       3|2010-12-01 08:34:00|     5.95|   13047.0|United Kingdom|
|   536367|    21755|LOVE BUILDING BLO...|       3|2010-12-01 08:34:00|     5.95|   13047.0|United Kingdom|
|   536367|    21777|RECIPE BOX WITH M...|       4|2010-12-01 08:34:00|     7.95|   13047.0|United Kingdom|
+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
only showing top 20 rows

In [ ]:
# Retorna linhas das colunas 'InvoiceNo' e 'Description' onde 'InvoiceNo' é diferente de 536365
from pyspark.sql.functions import col
df.where(col("InvoiceNo") != "536365") \
.select("InvoiceNo", "Description").show()

+---------+--------------------+
|InvoiceNo|         Description|
+---------+--------------------+
|   536366|HAND WARMER UNION...|
|   536366|HAND WARMER RED P...|
|   536367|ASSORTED COLOUR B...|
|   536367|POPPY'S PLAYHOUSE...|
|   536367|POPPY'S PLAYHOUSE...|
|   536367|FELTCRAFT PRINCES...|
|   536367|IVORY KNITTED MUG...|
|   536367|BOX OF 6 ASSORTED...|
|   536367|BOX OF VINTAGE JI...|
|   536367|BOX OF VINTAGE AL...|
|   536367|HOME BUILDING BLO...|
|   536367|LOVE BUILDING BLO...|
|   536367|RECIPE BOX WITH M...|
|   536367| DOORMAT NEW ENGLAND|
|   536368|JAM MAKING SET WI...|
|   536368|RED COAT RACK PAR...|
|   536368|YELLOW COAT RACK ...|
|   536368|BLUE COAT RACK PA...|
|   536369|BATH BUILDING BLO...|
|   536370|ALARM CLOCK BAKEL...|
+---------+--------------------+
only showing top 20 rows

In [ ]:
# usando o operador boleano com um predicado em uma expressão
df.where("InvoiceNo <> 536365").show()

+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
|InvoiceNo|StockCode|         Description|Quantity|        InvoiceDate|UnitPrice|CustomerID|       Country|
+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
|   536366|    22633|HAND WARMER UNION...|       6|2010-12-01 08:28:00|     1.85|   17850.0|United Kingdom|
|   536366|    22632|HAND WARMER RED P...|       6|2010-12-01 08:28:00|     1.85|   17850.0|United Kingdom|
|   536367|    84879|ASSORTED COLOUR B...|      32|2010-12-01 08:34:00|     1.69|   13047.0|United Kingdom|
|   536367|    22745|POPPY'S PLAYHOUSE...|       6|2010-12-01 08:34:00|      2.1|   13047.0|United Kingdom|
|   536367|    22748|POPPY'S PLAYHOUSE...|       6|2010-12-01 08:34:00|      2.1|   13047.0|United Kingdom|
|   536367|    22749|FELTCRAFT PRINCES...|       8|2010-12-01 08:34:00|     3.75|   13047.0|United Kingdom|
|   536367|    22310|IVORY KNITTED MUG...|       6|2010-12-01 08:34:00|     1.65|   13047.0|United Kingdom|
|   536367|    84969|BOX OF 6 ASSORTED...|       6|2010-12-01 08:34:00|     4.25|   13047.0|United Kingdom|
|   536367|    22623|BOX OF VINTAGE JI...|       3|2010-12-01 08:34:00|     4.95|   13047.0|United Kingdom|
|   536367|    22622|BOX OF VINTAGE AL...|       2|2010-12-01 08:34:00|     9.95|   13047.0|United Kingdom|
|   536367|    21754|HOME BUILDING BLO...|       3|2010-12-01 08:34:00|     5.95|   13047.0|United Kingdom|
|   536367|    21755|LOVE BUILDING BLO...|       3|2010-12-01 08:34:00|     5.95|   13047.0|United Kingdom|
|   536367|    21777|RECIPE BOX WITH M...|       4|2010-12-01 08:34:00|     7.95|   13047.0|United Kingdom|
|   536367|    48187| DOORMAT NEW ENGLAND|       4|2010-12-01 08:34:00|     7.95|   13047.0|United Kingdom|
|   536368|    22960|JAM MAKING SET WI...|       6|2010-12-01 08:34:00|     4.25|   13047.0|United Kingdom|
|   536368|    22913|RED COAT RACK PAR...|       3|2010-12-01 08:34:00|     4.95|   13047.0|United Kingdom|
|   536368|    22912|YELLOW COAT RACK ...|       3|2010-12-01 08:34:00|     4.95|   13047.0|United Kingdom|
|   536368|    22914|BLUE COAT RACK PA...|       3|2010-12-01 08:34:00|     4.95|   13047.0|United Kingdom|
|   536369|    21756|BATH BUILDING BLO...|       3|2010-12-01 08:35:00|     5.95|   13047.0|United Kingdom|
|   536370|    22728|ALARM CLOCK BAKEL...|      24|2010-12-01 08:45:00|     3.75|   12583.0|        France|
+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
only showing top 20 rows

In [ ]:
df.where("InvoiceNo == 536365").show(5)

+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
|InvoiceNo|StockCode|         Description|Quantity|        InvoiceDate|UnitPrice|CustomerID|       Country|
+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
|   536365|   85123A|WHITE HANGING HEA...|       6|2010-12-01 08:26:00|     2.55|   17850.0|United Kingdom|
|   536365|    71053| WHITE METAL LANTERN|       6|2010-12-01 08:26:00|     3.39|   17850.0|United Kingdom|
|   536365|   84406B|CREAM CUPID HEART...|       8|2010-12-01 08:26:00|     2.75|   17850.0|United Kingdom|
|   536365|   84029G|KNITTED UNION FLA...|       6|2010-12-01 08:26:00|     3.39|   17850.0|United Kingdom|
|   536365|   84029E|RED WOOLLY HOTTIE...|       6|2010-12-01 08:26:00|     3.39|   17850.0|United Kingdom|
+---------+---------+--------------------+--------+-------------------+---------+----------+--------------+
only showing top 5 rows

In [ ]:
# entendendo a ordem dos operadores boleanos
from pyspark.sql.functions import instr

priceFilter = col("UnitPrice") > 600
descripFilter = instr(df.Description, "POSTAGE") >=1

In [ ]:
# aplicando operadores como filtros
df.where(df.StockCode.isin("DOT")).where(priceFilter | descripFilter).show()

+---------+---------+--------------+--------+-------------------+---------+----------+--------------+
|InvoiceNo|StockCode|   Description|Quantity|        InvoiceDate|UnitPrice|CustomerID|       Country|
+---------+---------+--------------+--------+-------------------+---------+----------+--------------+
|   536544|      DOT|DOTCOM POSTAGE|       1|2010-12-01 14:32:00|   569.77|      null|United Kingdom|
|   536592|      DOT|DOTCOM POSTAGE|       1|2010-12-01 17:06:00|   607.49|      null|United Kingdom|
+---------+---------+--------------+--------+-------------------+---------+----------+--------------+

In [ ]:
# cria uma view ou tabela temporária
df.createOrReplaceTempView("dfTable")

In [ ]:
%sql
-- aplicando o mesmo código em SQL
select *
from dftable
where StockCode in ("DOT")
  and (UnitPrice > 600 or instr(Description, "POSTAGE") >=1)

InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
536544,DOT,DOTCOM POSTAGE,1,2010-12-01T14:32:00.000+0000,569.77,null,United Kingdom
536592,DOT,DOTCOM POSTAGE,1,2010-12-01T17:06:00.000+0000,607.49,null,United Kingdom

In [ ]:
# combinando filtros e operadores boleanos
from pyspark.sql.functions import instr

DOTCodeFilter = col("StockCode") == "DOT"
priceFilter = col("UnitPrice") > 600
descriptFilter = instr(col("Description"), "POSTAGE") >=1

In [ ]:
# combinando filtros e operadores boleanos
df.withColumn("e_caro", DOTCodeFilter & (priceFilter | descriptFilter))\
.where("e_caro")\
.select("UnitPrice", "e_caro").show(5)

+---------+------+
|UnitPrice|e_caro|
+---------+------+
|   569.77|  true|
|   607.49|  true|
+---------+------+

### Trabalhando com Joins

In [ ]:
# criando DataFrames
pessoa = spark.createDataFrame([
    (0, "João de Maria", 0, [100]),
    (1, "Norma Maria", 1, [500, 250, 100]),
    (2, "João de Deus", 1, [250, 100]),
    (3, "Ana Maria Silva", 4, [250, 100])
]).toDF("id", "name", "graduate_program", "spark_status")

programa_graduacao = spark.createDataFrame([
    (0, "Masters", "School of Information", "UC Berkeley"),
    (2, "Masters", "EECS", "UC Berkeley"),
    (1, "Ph.d", "EECS", "UC Berkeley")
]).toDF("id", "degree", "department", "school")

status = spark.createDataFrame([
    (500, "Vice President"),
    (250, "PMC Member"),
    (100, "Contributor")
]).toDF("id", "satus")

In [ ]:
# cria tabelas para os dataframes criados
pessoa.createOrReplaceTempView("pessoa")
programa_graduacao.createOrReplaceTempView("programa_graduacao")
status.createOrReplaceTempView("status")

In [ ]:
#imprime os dataframes
pessoa.show()
programa_graduacao.show()
status.show()

+---+---------------+----------------+---------------+
| id|           name|graduate_program|   spark_status|
+---+---------------+----------------+---------------+
|  0|  João de Maria|               0|          [100]|
|  1|    Norma Maria|               1|[500, 250, 100]|
|  2|   João de Deus|               1|     [250, 100]|
|  3|Ana Maria Silva|               4|     [250, 100]|
+---+---------------+----------------+---------------+

+---+-------+--------------------+-----------+
| id| degree|          department|     school|
+---+-------+--------------------+-----------+
|  0|Masters|School of Informa...|UC Berkeley|
|  2|Masters|                EECS|UC Berkeley|
|  1|   Ph.d|                EECS|UC Berkeley|
+---+-------+--------------------+-----------+

+---+--------------+
| id|         satus|
+---+--------------+
|500|Vice President|
|250|    PMC Member|
|100|   Contributor|
+---+--------------+

In [ ]:
# cria um objeto com as chaves para fazer o join
keys_join = pessoa["graduate_program"] == programa_graduacao["id"]

In [ ]:
# dataframe com inner join entre pessoa e programa de graduação
pessoa.join(programa_graduacao, keys_join).show()

+---+-------------+----------------+---------------+---+-------+--------------------+-----------+
| id|         name|graduate_program|   spark_status| id| degree|          department|     school|
+---+-------------+----------------+---------------+---+-------+--------------------+-----------+
|  0|João de Maria|               0|          [100]|  0|Masters|School of Informa...|UC Berkeley|
|  1|  Norma Maria|               1|[500, 250, 100]|  1|   Ph.d|                EECS|UC Berkeley|
|  2| João de Deus|               1|     [250, 100]|  1|   Ph.d|                EECS|UC Berkeley|
+---+-------------+----------------+---------------+---+-------+--------------------+-----------+

In [ ]:
# dataframe com inner join entre pessoa e programagraduação
# sintaxe join -->  dataframeprincipal.join(dataframealvo, condição_do_join, tipo_do_join)

pessoa.join(programa_graduacao, pessoa["graduate_program"] == programa_graduacao["id"], "inner").show()

+---+-------------+----------------+---------------+---+-------+--------------------+-----------+
| id|         name|graduate_program|   spark_status| id| degree|          department|     school|
+---+-------------+----------------+---------------+---+-------+--------------------+-----------+
|  0|João de Maria|               0|          [100]|  0|Masters|School of Informa...|UC Berkeley|
|  1|  Norma Maria|               1|[500, 250, 100]|  1|   Ph.d|                EECS|UC Berkeley|
|  2| João de Deus|               1|     [250, 100]|  1|   Ph.d|                EECS|UC Berkeley|
+---+-------------+----------------+---------------+---+-------+--------------------+-----------+

In [ ]:
# outer join: retorna null para linhas que não existam em um dos dataframes e retorna qualquer dado em qualquer dataframe, caso exista a chave

pessoa.join(programa_graduacao, keys_join, "outer").show()

+----+---------------+----------------+---------------+----+-------+--------------------+-----------+
|  id|           name|graduate_program|   spark_status|  id| degree|          department|     school|
+----+---------------+----------------+---------------+----+-------+--------------------+-----------+
|   0|  João de Maria|               0|          [100]|   0|Masters|School of Informa...|UC Berkeley|
|   1|    Norma Maria|               1|[500, 250, 100]|   1|   Ph.d|                EECS|UC Berkeley|
|   2|   João de Deus|               1|     [250, 100]|   1|   Ph.d|                EECS|UC Berkeley|
|null|           null|            null|           null|   2|Masters|                EECS|UC Berkeley|
|   3|Ana Maria Silva|               4|     [250, 100]|null|   null|                null|       null|
+----+---------------+----------------+---------------+----+-------+--------------------+-----------+

In [ ]:
# left join: retorna null para linhas que não existam no dataframe da direita
pessoa.join(programa_graduacao, keys_join, "left").show()

+---+---------------+----------------+---------------+----+-------+--------------------+-----------+
| id|           name|graduate_program|   spark_status|  id| degree|          department|     school|
+---+---------------+----------------+---------------+----+-------+--------------------+-----------+
|  0|  João de Maria|               0|          [100]|   0|Masters|School of Informa...|UC Berkeley|
|  1|    Norma Maria|               1|[500, 250, 100]|   1|   Ph.d|                EECS|UC Berkeley|
|  2|   João de Deus|               1|     [250, 100]|   1|   Ph.d|                EECS|UC Berkeley|
|  3|Ana Maria Silva|               4|     [250, 100]|null|   null|                null|       null|
+---+---------------+----------------+---------------+----+-------+--------------------+-----------+

In [ ]:
# right join: retorna null para linhas que não existam no dataframe da direita
pessoa.join(programa_graduacao, keys_join, "right").show()

+----+-------------+----------------+---------------+---+-------+--------------------+-----------+
|  id|         name|graduate_program|   spark_status| id| degree|          department|     school|
+----+-------------+----------------+---------------+---+-------+--------------------+-----------+
|   0|João de Maria|               0|          [100]|  0|Masters|School of Informa...|UC Berkeley|
|null|         null|            null|           null|  2|Masters|                EECS|UC Berkeley|
|   2| João de Deus|               1|     [250, 100]|  1|   Ph.d|                EECS|UC Berkeley|
|   1|  Norma Maria|               1|[500, 250, 100]|  1|   Ph.d|                EECS|UC Berkeley|
+----+-------------+----------------+---------------+---+-------+--------------------+-----------+

In [ ]:
# inserindo mais condições aos joins
keys_join = (pessoa["graduate_program"] == programa_graduacao["id"]) & (pessoa["graduate_program"] > 0)
pessoa.join(programa_graduacao, keys_join).show()

+---+------------+----------------+---------------+---+------+----------+-----------+
| id|        name|graduate_program|   spark_status| id|degree|department|     school|
+---+------------+----------------+---------------+---+------+----------+-----------+
|  1| Norma Maria|               1|[500, 250, 100]|  1|  Ph.d|      EECS|UC Berkeley|
|  2|João de Deus|               1|     [250, 100]|  1|  Ph.d|      EECS|UC Berkeley|
+---+------------+----------------+---------------+---+------+----------+-----------+

In [ ]:
# condições mais complexas

from pyspark.sql.functions import expr

pessoa.withColumnRenamed("id", "personID").join(status, expr("array_contains(spark_status, id)")).show()

+--------+---------------+----------------+---------------+---+--------------+
|personID|           name|graduate_program|   spark_status| id|         satus|
+--------+---------------+----------------+---------------+---+--------------+
|       0|  João de Maria|               0|          [100]|100|   Contributor|
|       1|    Norma Maria|               1|[500, 250, 100]|500|Vice President|
|       1|    Norma Maria|               1|[500, 250, 100]|250|    PMC Member|
|       1|    Norma Maria|               1|[500, 250, 100]|100|   Contributor|
|       2|   João de Deus|               1|     [250, 100]|250|    PMC Member|
|       2|   João de Deus|               1|     [250, 100]|100|   Contributor|
|       3|Ana Maria Silva|               4|     [250, 100]|250|    PMC Member|
|       3|Ana Maria Silva|               4|     [250, 100]|100|   Contributor|
+--------+---------------+----------------+---------------+---+--------------+

### Trabalhando com UDF's (funções definidas por usuários)
* Integração de códigos entre as APIs
* É Preciso cuidado com performance dos códigos usando UDFs

In [ ]:
from pyspark.sql.types import LongType
# definindo a função exemplo
def quadrado(s):
    return s * s

In [ ]:
# registra no banco de dados do spark e define o tipo de retorno, por padrão é stringtype
from pyspark.sql.types import LongType
spark.udf.register("func_Py_quadrado", quadrado, LongType())

Out[83]: <function __main__.quadrado(s)>

In [ ]:
# gerando valores aleatórios para exemplo
spark.range(1, 20).show()

+---+
| id|
+---+
|  1|
|  2|
|  3|
|  4|
|  5|
|  6|
|  7|
|  8|
|  9|
| 10|
| 11|
| 12|
| 13|
| 14|
| 15|
| 16|
| 17|
| 18|
| 19|
+---+

In [ ]:
# cria a visão View_temp
spark.range(1, 20).createOrReplaceTempView("View_temp")

In [ ]:
%sql
-- usando a função criada em python juntamente com sql 
select id, func_Py_quadrado(id) as id_ao_quadrado
from view_temp

id,id_ao_quadrado
1,1
2,4
3,9
4,16
5,25
6,36
7,49
8,64
9,81
10,100
11,121
12,144
13,169
14,196
15,225
16,256
17,289
18,324
19,361

### UDFs com Dataframes

In [ ]:
from pyspark.sql.functions import udf
from pyspark.sql.types import LongType
# registra a UDF
func_Py_quadrado = udf(quadrado, LongType())

In [ ]:
# cria um datagrame a partir da tabela temporária
df = spark.table("View_temp")

In [ ]:
df.show()

+---+
| id|
+---+
|  1|
|  2|
|  3|
|  4|
|  5|
|  6|
|  7|
|  8|
|  9|
| 10|
| 11|
| 12|
| 13|
| 14|
| 15|
| 16|
| 17|
| 18|
| 19|
+---+

In [ ]:
# usando o dataframe juntamente com a UDF registrada
df.select("id", func_Py_quadrado("id").alias("quadrado")).show()

+---+--------+
| id|quadrado|
+---+--------+
|  1|       1|
|  2|       4|
|  3|       9|
|  4|      16|
|  5|      25|
|  6|      36|
|  7|      49|
|  8|      64|
|  9|      81|
| 10|     100|
| 11|     121|
| 12|     144|
| 13|     169|
| 14|     196|
| 15|     225|
| 16|     256|
| 17|     289|
| 18|     324|
| 19|     361|
+---+--------+

### Koalas - desatualizado

In [ ]:
import numpy as np
import pandas as pd
import pyspark.pandas as ps

In [ ]:
# criando um dataframe
pdf = pd.DataFrame({
    'A': np.random.rand(5),
    'B': np.random.rand(5)
})

In [ ]:
type(pdf)

Out[98]: pandas.core.frame.DataFrame

In [ ]:
psdf = ps.DataFrame(pdf)
type(psdf)

Out[100]: pyspark.pandas.frame.DataFrame

In [ ]:
pdf.head()

,A,B
0,0.785895,0.439112
1,0.197983,0.879104
2,0.110190,0.434834
3,0.611616,0.897550
4,0.691005,0.354656

In [ ]:
psdf.head()

,A,B
0,0.785895,0.439112
1,0.197983,0.879104
2,0.110190,0.434834
3,0.611616,0.897550
4,0.691005,0.354656

In [ ]:
psdf.describe().T

,count,mean,std,min,25%,50%,75%,max
A,5.0,0.479338,0.304840,0.110190,0.197983,0.611616,0.691005,0.785895
B,5.0,0.601051,0.264475,0.354656,0.434834,0.439112,0.879104,0.897550

In [ ]:
psdf.info()

<class 'pyspark.pandas.frame.DataFrame'>
Int64Index: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      float64
 1   B       5 non-null      float64
dtypes: float64(2)

In [ ]:
# ordenando um dataframe
psdf.sort_values(by='B')

,A,B
4,0.691005,0.354656
2,0.110190,0.434834
0,0.785895,0.439112
1,0.197983,0.879104
3,0.611616,0.897550

In [ ]:
# define configurações de layout de células
from pyspark.pandas.config import set_option, get_option
ps.get_option('compute.max_rows')
ps.set_option('compute.max_rows', 2000)

In [ ]:
# slice
psdf[['A', 'B']]

,A,B
0,0.785895,0.439112
1,0.197983,0.879104
2,0.110190,0.434834
3,0.611616,0.897550
4,0.691005,0.354656

In [ ]:
# iloc
psdf.iloc[:3, 1:2]

,B
0,0.439112
1,0.879104
2,0.434834

### Usando funções python

In [ ]:
# criando função python
def quadrado(x):
    return x ** 2

In [ ]:
# habilitar computação de dataframes em séries
from pyspark.pandas.config import set_option, reset_option
set_option("compute.ops_on_diff_frames", True)

In [ ]:
# cria uma nova coluna a partir da função quadrado
psdf['C'] = psdf.A.apply(quadrado)

In [ ]:
psdf.head()

,A,B,C
0,0.785895,0.439112,0.617631
1,0.197983,0.879104,0.039197
2,0.110190,0.434834,0.012142
3,0.611616,0.897550,0.374074
4,0.691005,0.354656,0.477488

In [ ]:
psdf.groupby('A').sum()

,B,C
A,,
0.785895,0.439112,0.617631
0.197983,0.879104,0.039197
0.110190,0.434834,0.012142
0.611616,0.897550,0.374074
0.691005,0.354656,0.477488

In [ ]:
psdf.groupby(['A', 'B']).sum()

,,C
A,B,
0.785895,0.439112,0.617631
0.197983,0.879104,0.039197
0.110190,0.434834,0.012142
0.611616,0.897550,0.374074
0.691005,0.354656,0.477488